esphome:
  name: esp8266-538340

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key 

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bme280-Test Fallback Hotspot"
    password: "ZNZJHJ5gkVZr"

i2c:
  sda: D3
  scl: D4
  scan: true

# configure BME280
sensor:
  - platform: bme280_i2c
    temperature:
      name: "BME280 Temperature"
      internal: true  # <--- Stops automatic MQTT publishing
    pressure:
      name: "BME280 Pressure"
      internal: true  # <--- Stops automatic MQTT publishing
    humidity:
      name: "BME280 Humidity"
      internal: true  # <--- Stops automatic MQTT publishing
    address: 0x76
    update_interval: 60s

time:
  - platform: sntp
    id: sntp_time
    timezone: America/Chicago
    servers:
     - 0.pool.ntp.org
     - 1.pool.ntp.org
     - 2.pool.ntp.org

# Example configuration entry
mqtt:
  broker: !secret mqtt_broker
  log_topic:
    topic: debug
    level: ERROR
  discovery: false 
  
captive_portal:
    